#!/usr/bin/env python3
"""Generate per-type JSON-Schema mirrors from `maintenance/schemas/header-ontology.json`.

The canonical machine-readable source for the frontmatter ontology is
`maintenance/schemas/header-ontology.json` — that file binds
`tools/fm/validate.py`. This generator emits stand-alone JSON-Schema
draft-07 documents under `maintenance/schemas/` so external agents
(Jules, Gemini) can validate operational frontmatter with a vendored
`jsonschema` library, without cloning this repo or importing its
Python.

Mirrors are derived artefacts. They MUST NOT be edited by hand. The
divergence gate in `tools/check-governance.sh` re-runs the generator
on every commit and fails if the on-disk mirrors disagree with what
the ontology would produce.

Usage:
    python3 tools/fm/gen_schema_mirror.py [--check] [--out DIR]

    --check   Exit 1 if any mirror on disk differs from generated output
              (no files written). Used by the pre-commit gate.
    --out     Output directory (default: maintenance/schemas/).

Closes Task 023; successor to Task 011.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
ONTOLOGY_PATH = REPO_ROOT / "maintenance" / "schemas" / "header-ontology.json"
DEFAULT_OUT = REPO_ROOT / "maintenance" / "schemas"

L2_TYPES = ["task", "prompt", "research", "skill", "adr"]

DATE_PATTERN = r"^\d{4}-\d{2}-\d{2}$"
SLUG_PATTERN = r"^[a-z0-9][a-z0-9-]*$"


def _l1_properties(ontology: dict) -> dict:
    return {
        "type":    {"type": "string", "enum": ontology["type_values"]},
        "status":  {"type": "string", "enum": ontology["status_values"]},
        "slug":    {"type": "string", "pattern": SLUG_PATTERN},
        "summary": {"type": "string", "minLength": 1},
        "created": {"type": "string", "pattern": DATE_PATTERN},
        "updated": {"type": "string", "pattern": DATE_PATTERN},
    }


def build_l1_schema(ontology: dict) -> dict:
    return {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": "https://github.com/netzkontrast/agency/maintenance/schemas/l1-vault-core.schema.json",
        "title": "L1 Vault Core frontmatter (mandatory for operational files)",
        "description": (
            "Mirror of header-ontology.json `l1_required`. Generated by "
            "tools/fm/gen_schema_mirror.py — do not edit by hand."
        ),
        "type": "object",
        "properties": _l1_properties(ontology),
        "required": list(ontology["l1_required"]),
        "additionalProperties": True,
    }


def _typed_l2_field(key: str, ontology: dict) -> dict:
    """Best-effort type inference for L2 keys from the ontology vocabulary."""
    if key == "task_status":
        return {"type": "string", "enum": ontology["task_status_values"]}
    if key == "task_priority":
        return {"type": "string", "enum": ["P0", "P1", "P2", "P3"]}
    if key.endswith("_id"):
        return {"type": "string", "minLength": 1}
    list_suffixes = (
        "_uses_prompts", "_spawns_research", "_spawns_prompts",
        "_affects_paths", "_blocked_by", "_supersedes", "_superseded_by",
        "_uses", "_complements", "_triggers", "_target_agents", "_tags",
    )
    if any(key.endswith(suf) for suf in list_suffixes):
        return {"type": "array", "items": {"type": "string"}}
    return {"type": "string"}


def build_l2_schema(t: str, ontology: dict) -> dict:
    spec = ontology["types"][t]

    if t == "adr" and "json_schema" in spec:
        out = dict(spec["json_schema"])
        out.setdefault("$schema", "http://json-schema.org/draft-07/schema#")
        out["$id"] = (
            f"https://github.com/netzkontrast/agency/"
            f"maintenance/schemas/l2-{t}.schema.json"
        )
        out["title"] = spec["json_schema"].get(
            "title", f"ADR L1 + adr_* L2 namespace"
        )
        out["description"] = (
            "Mirror lifted from header-ontology.json types.adr.json_schema. "
            "Generated by tools/fm/gen_schema_mirror.py — do not edit by hand."
        )
        return out

    properties = _l1_properties(ontology)
    if t == "task":
        properties["type"] = {"const": "task"}
    elif t == "prompt":
        properties["type"] = {"const": "prompt"}
    elif t == "research":
        properties["type"] = {"const": "research"}
    elif t == "skill":
        properties = {}

    for key in spec.get("required_keys", []):
        if key in properties:
            continue
        properties[key] = _typed_l2_field(key, ontology)
    for key in spec.get("recommended_keys", []):
        if key in properties:
            continue
        properties[key] = _typed_l2_field(key, ontology)

    schema = {
        "$schema": "http://json-schema.org/draft-07/schema#",
        "$id": (
            f"https://github.com/netzkontrast/agency/"
            f"maintenance/schemas/l2-{t}.schema.json"
        ),
        "title": f"L1 + {t}_* L2 namespace",
        "description": (
            f"Mirror of header-ontology.json types.{t}. Generated by "
            "tools/fm/gen_schema_mirror.py — do not edit by hand."
        ),
        "type": "object",
        "properties": properties,
        "required": list(spec.get("required_keys", [])),
        "additionalProperties": True,
    }
    return schema


def build_all(ontology: dict) -> dict[str, dict]:
    out = {"l1-vault-core": build_l1_schema(ontology)}
    for t in L2_TYPES:
        if t not in ontology["types"]:
            continue
        out[f"l2-{t}"] = build_l2_schema(t, ontology)
    return out


def _serialise(schema: dict) -> str:
    return json.dumps(schema, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 on divergence; do not write files.")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    if not ONTOLOGY_PATH.exists():
        print(f"ERROR: ontology not found at {ONTOLOGY_PATH}", file=sys.stderr)
        return 2

    ontology = json.loads(ONTOLOGY_PATH.read_text(encoding="utf-8"))
    schemas = build_all(ontology)
    out_dir: Path = args.out
    out_dir.mkdir(parents=True, exist_ok=True)

    diverged: list[str] = []
    for name, schema in schemas.items():
        target = out_dir / f"{name}.schema.json"
        body = _serialise(schema)
        if args.check:
            existing = target.read_text(encoding="utf-8") if target.exists() else ""
            if existing != body:
                diverged.append(str(target.relative_to(REPO_ROOT)))
        else:
            target.write_text(body, encoding="utf-8")
            print(f"wrote {target.relative_to(REPO_ROOT)}")

    if args.check and diverged:
        print(
            "ERROR: JSON-Schema mirrors diverge from header-ontology.json. "
            "Regenerate with `python3 tools/fm/gen_schema_mirror.py`:",
            file=sys.stderr,
        )
        for path in diverged:
            print(f"  {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
