// Agency Repository — Real Data from netzkontrast/agency@main
// Generated 2026-05-05

window.AGENCY_DATA = {
  tasks: [
    { id: "000", slug: "decouple-architecture", status: "done", priority: "P0", owner: "claude-code", summary: "Bootstrap meta-task: introduce /tasks/, the Frontmatter Ontology, TASK.md, refactor PROMPT.md/RESEARCH.md/FOLDERS.md, ship templates and a frontmatter validator.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: [], spawns_research: [] },
    { id: "001", slug: "refactor-governance-from-specs", status: "open", priority: "P1", owner: null, summary: "Encode rules from Spec-A/B/C, Spec-G/H/I, and Spec-J/K/L into linters, hooks, and templates.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: ["refactor-governance-from-specs"], spawns_research: [] },
    { id: "002", slug: "token-efficiency-tool-suite", status: "done", priority: "P1", owner: "claude-code", summary: "Build token-efficiency tooling for agentic workflows.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: ["token-efficiency-tool-suite"], spawns_research: ["token-efficiency-tool-suite"] },
    { id: "003", slug: "analyze-skillmd-novel-authoring", status: "done", priority: "P2", owner: "claude-code", summary: "Analyze Gemini SKILL.md novel-authoring research (DE/EN) and extract actionable recommendations.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: ["github-skillmd-novel-authoring-de-en"], spawns_research: [] },
    { id: "004", slug: "create-missing-prompts", status: "updated", priority: "P2", owner: null, summary: "Author missing prompts for Tasks 001 and 002. Superseded by Task 020.", created: "2026-05-04", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "005", slug: "address-deferred-coherence-issues", status: "updated", priority: "P1", owner: null, summary: "Apply 148 deferred T1/T2 frontmatter stubs from coherence run 2026-05-04. Superseded by Task 021.", created: "2026-05-04", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "006a", slug: "skills-navigation-bootstrap", status: "open", priority: "P2", owner: null, summary: "Bootstrap navigation structure for /skills/ directory.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: ["skills-navigation-bootstrap"], spawns_research: ["skills-navigation-bootstrap"] },
    { id: "006b", slug: "surface-skills-architecture", status: "open", priority: "P1", owner: null, summary: "Surface skills-skill-architecture research findings to root governance. Renumbered from 003.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: ["skills-skill-architecture"], spawns_research: ["skills-skill-architecture"] },
    { id: "007", slug: "reconcile-closed-task-linkage", status: "open", priority: "P2", owner: null, summary: "Reconcile linkage drift in closed Tasks 002 and 003 (missing friction-logs, prompt/research field confusion).", created: "2026-05-04", updated: "2026-05-04", uses_prompts: [], spawns_research: [] },
    { id: "008", slug: "harden-coherence-baseline-protocol", status: "open", priority: "P1", owner: null, summary: "Harden the coherence-check baseline + run-log protocol against squash-merges, malformed records, duplicate task_ids.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: ["repo-coherence-check"], spawns_research: [] },
    { id: "009a", slug: "author-skills-root-spec", status: "open", priority: "P1", owner: null, summary: "Author SKILLS.md, the missing root governance spec for /skills/, and wire skill-to-skill cross-references.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: ["author-skills-root-spec"], spawns_research: [] },
    { id: "009b", slug: "review-pr28-readme-spec", status: "open", priority: "P2", owner: null, summary: "Review PR #28 introducing the README update spec.", created: "2026-05-04", updated: "2026-05-04", uses_prompts: ["pr27-governance-review"], spawns_research: ["pr27-governance-review"] },
    { id: "010", slug: "skills-frontmatter-index-suite", status: "updated", priority: "P2", owner: null, summary: "Build the token-efficient frontmatter index + skills tool suite. Superseded by Task 022.", created: "2026-05-04", updated: "2026-05-05", uses_prompts: ["skills-frontmatter-index-suite"], spawns_research: [] },
    { id: "011", slug: "skills-frontmatter-schema-files", status: "updated", priority: "P2", owner: null, summary: "Author JSON Schemas for L1/L2 frontmatter and the canonical header ontology. Superseded by Task 023.", created: "2026-05-04", updated: "2026-05-05", uses_prompts: ["skills-frontmatter-schema-files"], spawns_research: [] },
    { id: "012", slug: "review-pr-29", status: "in_progress", priority: "P1", owner: "claude-code", summary: "Structured code review of PR #29 (skills governance, Tasks 009–011).", created: "2026-05-04", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "013", slug: "renumber-duplicate-task-ids", status: "updated", priority: "P2", owner: null, summary: "Resolve duplicate task_id collisions for ids 006 and 009. Superseded by Task 024.", created: "2026-05-04", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "014", slug: "improve-maintenance-spec-from-session", status: "updated", priority: "P2", owner: null, summary: "Capture maintenance-spec improvements from 2026-05-05 coherence run. Superseded by Task 025.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "015", slug: "integrate-dramatica-ncp-skills", status: "in_progress", priority: "P1", owner: "claude-code", summary: "Spec-driven restructure of Dramatica skills with deep ncp-author + novel-architect integration via Narrative Ontology.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: ["integrate-dramatica-ncp-skills"], spawns_research: ["integrate-dramatica-ncp-skills"] },
    { id: "016", slug: "flexible-frontmatter-toolchain", status: "open", priority: "P0", owner: null, summary: "Implement four-tool stateless toolchain (fm-validate / fm-extract / fm-edit / fm-query) per SPEC.md.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: ["build-flexible-frontmatter-toolchain", "flexible-frontmatter-toolchain"], spawns_research: ["flexible-frontmatter-toolchain"] },
    { id: "017", slug: "migrate-repo-to-flexible-toolchain", status: "blocked", priority: "P1", owner: null, summary: "Migrate the repo onto the flexible toolchain in three batches; retire legacy linters. Blocked on Task 016.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: ["migrate-repo-to-flexible-toolchain"], spawns_research: [] },
    { id: "018", slug: "fm-section-editor", status: "open", priority: "P2", owner: null, summary: "Build the fm-section editor (replace/append/insert/delete/rename) per SPEC §13.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "019", slug: "fm-toolchain-suite-integration", status: "open", priority: "P1", owner: null, summary: "Decompose gap between fm-* atomic surface and complete authoring/refactoring/validation toolchain into nine parallelizable subtasks.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "020", slug: "audit-prompt-fm-validate-conformance", status: "open", priority: "P2", owner: null, summary: "Bring every /prompts/<slug>/prompt.md into conformance with the prompt-type required-headings contract.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "021", slug: "apply-fm-edit-to-deferred-coherence", status: "open", priority: "P2", owner: null, summary: "Apply deferred T1/T2 frontmatter stubs via tools/fm/edit.py after Task 017 migration completes. Blocked by 017.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "022", slug: "skills-query-cli-atop-fm-query", status: "open", priority: "P2", owner: null, summary: "Thin skills-query convenience wrapper atop stateless tools/fm/query.py; no persistent index. Blocked by 019.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "023", slug: "header-ontology-and-schema-mirror", status: "open", priority: "P2", owner: null, summary: "Add the per-type JSON Schema mirror (generated from header-ontology.json) plus a divergence gate.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "024", slug: "renumber-duplicate-task-ids-v2", status: "open", priority: "P2", owner: null, summary: "Renumber the persistent 006/006 and 009/009 duplicates into the next free slots.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
    { id: "025", slug: "maintenance-spec-remaining-findings", status: "open", priority: "P2", owner: null, summary: "Carry forward F2/F3/F4/F7 from maintenance spec improvements. Blocked by 019.", created: "2026-05-05", updated: "2026-05-05", uses_prompts: [], spawns_research: [] },
  ],

  prompts: [
    { slug: "author-skills-root-spec", kind: "task-spec", relates_to_task: "009a", summary: "Task-spec prompt that authors SKILLS.md at the repository root, plus supporting edits to AGENTS.md / FOLDERS.md / templates.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "budget-enforcer-fallback", kind: "tool-instruction", relates_to_task: null, summary: "Tool instruction for budget enforcement fallback behaviour in agentic sessions.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "build-flexible-frontmatter-toolchain", kind: "task-spec", relates_to_task: "016", summary: "Task-spec prompt for Task 016 (build the four-tool CLI surface + header-ontology JSON).", created: "2026-05-05", updated: "2026-05-05" },
    { slug: "claude-ai-container-git-verification", kind: "tool-instruction", relates_to_task: null, summary: "Tool instruction for verifying git state inside Claude AI containers.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "context-pruner-differentiation", kind: "research-proposal", relates_to_task: null, summary: "Research proposal for differentiating context-pruner strategies.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "cross-skill-context-poisoning", kind: "research-proposal", relates_to_task: null, summary: "Research proposal on cross-skill context poisoning vectors.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "flexible-frontmatter-toolchain", kind: "research-proposal", relates_to_task: "016", summary: "Research-proposal that synthesises prior research + skill-creator into a flexible maintenance contract plus stateless toolchain spec.", created: "2026-05-05", updated: "2026-05-05" },
    { slug: "github-skillmd-novel-authoring-de-en", kind: "research-proposal", relates_to_task: "003", summary: "Research proposal: Gemini analysis of GitHub repos with SKILL.md-conformant novel-authoring capabilities (DE/EN).", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "integrate-dramatica-ncp-skills", kind: "task-spec", relates_to_task: "015", summary: "Task-spec for Dramatica skills restructure with NCP + novel-architect integration via Narrative Ontology.", created: "2026-05-05", updated: "2026-05-05" },
    { slug: "mega-context-limit-management", kind: "tool-instruction", relates_to_task: null, summary: "Tool instruction for managing mega-context limits in long agentic sessions.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "migrate-repo-to-flexible-toolchain", kind: "task-spec", relates_to_task: "017", summary: "Task-spec for Task 017 (three-batch migration; retires legacy linters; scope-narrows Task 010).", created: "2026-05-05", updated: "2026-05-05" },
    { slug: "pr27-governance-review", kind: "research-proposal", relates_to_task: "009b", summary: "Structured governance review prompt for PR #27.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "refactor-governance-from-specs", kind: "task-spec", relates_to_task: "001", summary: "Task-spec for encoding Spec-A/B/C, G/H/I, J/K/L rules into linters, hooks, and templates.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "repo-coherence-check", kind: "tool-instruction", relates_to_task: "008", summary: "Tool instruction for running the nightly Repo Coherence Check protocol.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "research-prompt-from-annotations", kind: "research-proposal", relates_to_task: null, summary: "A prompt that scans an existing research folder for open questions and generates new research prompts from findings.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-frontmatter-index-suite", kind: "task-spec", relates_to_task: "010", summary: "Research-proposal + build prompt for token-efficient frontmatter index, query CLI, and skills manifest emitter.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-frontmatter-schema-files", kind: "task-spec", relates_to_task: "011", summary: "Task-spec prompt for JSON Schemas for L1/L2 frontmatter and header ontology.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-manifest-emission-tool", kind: "tool-instruction", relates_to_task: null, summary: "Tool instruction for emitting the skills manifest from frontmatter index.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-namespace-ontology", kind: "research-proposal", relates_to_task: null, summary: "Research proposal for the skill_* L2 namespace ratification.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-navigation-bootstrap", kind: "task-spec", relates_to_task: "006a", summary: "Task-spec for bootstrapping navigation structure for /skills/ directory.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-skill-architecture", kind: "research-proposal", relates_to_task: "006b", summary: "Research proposal on skills architecture design patterns and contracts.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-skill-container-capabilities", kind: "research-proposal", relates_to_task: null, summary: "Research proposal on container capabilities available to running skills.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-skill-enterprise-offline", kind: "research-proposal", relates_to_task: null, summary: "Research proposal on enterprise offline skill deployment patterns.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-skill-gemini-cli-portability", kind: "research-proposal", relates_to_task: null, summary: "Research proposal on Gemini CLI portability for skills.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-skill-jules-portability", kind: "research-proposal", relates_to_task: null, summary: "Research proposal on Jules agent portability for skills.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-skill-trigger-lifecycle", kind: "research-proposal", relates_to_task: null, summary: "Research proposal on trigger lifecycle for skills execution.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "subjective-quality-evaluation", kind: "research-proposal", relates_to_task: null, summary: "Research proposal on subjective quality evaluation metrics for agentic output.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "token-efficiency-tool-suite", kind: "task-spec", relates_to_task: "002", summary: "Task-spec for building token-efficiency tooling for agentic workflows.", created: "2026-05-04", updated: "2026-05-04" },
  ],

  research: [
    { slug: "agent-prompt-specs-3-systems-sdd", phase: "complete", executes_prompt: "refactor-governance-from-specs", summary: "Spec-A/B/C: agentic prompt specifications (3-systems SDD).", created: "2026-05-02", updated: "2026-05-04" },
    { slug: "agentic-eval-trust-improvement-spec", phase: "complete", executes_prompt: null, summary: "Spec-J/K/L: evaluation, trust, improvement loops for agentic systems.", created: "2026-05-02", updated: "2026-05-04" },
    { slug: "agentic-session-continuity-spec", phase: "complete", executes_prompt: null, summary: "Spec-G/H/I: session continuity across agentic runs.", created: "2026-05-02", updated: "2026-05-04" },
    { slug: "flexible-frontmatter-toolchain", phase: "complete", executes_prompt: "flexible-frontmatter-toolchain", summary: "Synthesis run: distils prior research into a flexible maintenance contract plus stateless fm-validate/extract/edit/query toolchain.", created: "2026-05-05", updated: "2026-05-05" },
    { slug: "integrate-dramatica-ncp-skills", phase: "in_progress", executes_prompt: "integrate-dramatica-ncp-skills", summary: "Narrative Ontology schema + navigator suite for Dramatica × NCP × novel-architect integration.", created: "2026-05-05", updated: "2026-05-05" },
    { slug: "ncp-novel-co-authoring-spec", phase: "complete", executes_prompt: null, summary: "Narrative Context Protocol / Dramatica integration spec for novel co-authoring.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "obsidian-frontmatter-agentic-spec", phase: "complete", executes_prompt: null, summary: "The Layered Schema with Namespacing model backing this repo's frontmatter ontology.", created: "2026-05-02", updated: "2026-05-04" },
    { slug: "pr27-governance-review", phase: "complete", executes_prompt: "pr27-governance-review", summary: "Structured review of PR #27 governance changes.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "repo-maintenance-protocol-spec", phase: "complete", executes_prompt: "repo-coherence-check", summary: "Nightly maintenance protocol spec and Repo Coherence Check procedure.", created: "2026-05-04", updated: "2026-05-05" },
    { slug: "skills-namespace-ontology", phase: "complete", executes_prompt: "skills-namespace-ontology", summary: "Ratified skill_* L2 namespace: five kind values, three tier values, 14-skill mapping.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-navigation-bootstrap", phase: "complete", executes_prompt: "skills-navigation-bootstrap", summary: "Navigation bootstrap output for /skills/ directory.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-skill-architecture", phase: "complete", executes_prompt: "skills-skill-architecture", summary: "Skills architecture design patterns, contracts, and cross-agent navigation.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "skills-skill-container-capabilities", phase: "complete", executes_prompt: "skills-skill-container-capabilities", summary: "Container capabilities available to running skills in Claude Code.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "spec-driven-research-agentic-workflows", phase: "complete", executes_prompt: null, summary: "Spec-driven research workflow patterns for long-horizon agentic projects.", created: "2026-05-04", updated: "2026-05-04" },
    { slug: "token-efficiency-tool-suite", phase: "complete", executes_prompt: "token-efficiency-tool-suite", summary: "Token-efficiency tooling output: context pruner, budget enforcer, manifest emitter.", created: "2026-05-04", updated: "2026-05-05" },
    { slug: "gemini/github-skillmd-novel-authoring-de-en", phase: "complete", executes_prompt: "github-skillmd-novel-authoring-de-en", summary: "External: Gemini analysis of GitHub repos with SKILL.md novel-authoring capabilities (DE/EN).", created: "2026-05-04", updated: "2026-05-04" },
  ],

  frictionLogs: [
    { task: "000", level: "FL0", session: "2026-05-04T09:14Z", agent: "claude-code", duration: "1h 42m", tokens: 184320, note: "Zero friction. Architecture decoupling executed cleanly. All linters passed first-try; templates accepted by validator without amendment." },
    { task: "002", level: "FL1", session: "2026-05-04T11:30Z", agent: "claude-code", duration: "2h 18m", tokens: 221504, note: "Minor friction: token counting edge cases in Python stdlib for non-ASCII content. Resolved with explicit utf-8 encoding pass + tiktoken fallback. Two re-runs." },
    { task: "003", level: "FL0", session: "2026-05-04T14:02Z", agent: "claude-code", duration: "47m", tokens: 92160, note: "Clean analysis run. Gemini output was well-structured; extraction template fit on first pass." },
    { task: "012", level: "FL2", session: "2026-05-05T09:50Z", agent: "claude-code", duration: "3h 04m", tokens: 318720, note: "PR #29 had linkage violations: prompts referenced non-existent task ids and one research workspace was missing executes_prompt frontmatter. Required manual triage + ad-hoc patch script before review could proceed. Recommend: hard pre-commit gate on cross-link integrity (Task 008)." },
    { task: "015", level: "FL1", session: "2026-05-05T13:22Z", agent: "claude-code", duration: "2h 11m", tokens: 246784, note: "Dramatica ontology cross-references required multiple passes to validate against NCP schema. Synthesis loop converged on 3rd iteration." },
    { task: "016", level: "FL3", session: "2026-05-05T16:40Z", agent: "claude-code", duration: "4h 22m", tokens: 412160, note: "BLOCKING: fm-edit semantics underspecified for nested-list mutations. Spec ambiguous between merge and replace; produced two divergent implementations. Halted execution pending human disambiguation." },
    { task: "017", level: "FL2", session: "2026-05-05T18:00Z", agent: "claude-code", duration: "44m", tokens: 61440, note: "Cannot proceed: blocked by 016. Captured migration plan as artefact and exited cleanly." },
  ],

  precommitRuns: [
    { id: "pc-2026-05-05-1840", ts: "2026-05-05T18:40:12Z", branch: "main", commit: "a3f7c91", author: "claude-code", status: "pass",   duration: "12.4s", checks: [
      { id: "frontmatter-validate", status: "pass", details: "All 70 docs validated against L1/L2 schema" },
      { id: "task-prompt-link",     status: "pass", details: "All task→prompt references resolve" },
      { id: "research-prompt-link", status: "pass", details: "All research→prompt references resolve" },
      { id: "duplicate-task-id",    status: "warn", details: "2 known duplicates: 006a/006b, 009a/009b (tracked: Task 024)" },
      { id: "stale-frontmatter",    status: "pass", details: "No docs older than 14 days without `updated`" },
      { id: "coherence-check",      status: "pass", details: "Audit graph closure verified" },
    ]},
    { id: "pc-2026-05-05-1605", ts: "2026-05-05T16:05:48Z", branch: "task-016-fm-toolchain", commit: "82ba0e2", author: "claude-code", status: "fail", duration: "8.9s", checks: [
      { id: "frontmatter-validate", status: "pass", details: "All docs validated" },
      { id: "task-prompt-link",     status: "fail", details: "task 016 references prompt `flexible-frontmatter-toolchain` but prompt frontmatter `relates_to_task` = null (expected: 016)" },
      { id: "research-prompt-link", status: "pass", details: "OK" },
      { id: "duplicate-task-id",    status: "warn", details: "2 known duplicates" },
      { id: "stale-frontmatter",    status: "pass", details: "OK" },
      { id: "coherence-check",      status: "skip", details: "Skipped: prior check failed" },
    ]},
    { id: "pc-2026-05-05-1422", ts: "2026-05-05T14:22:03Z", branch: "task-015-dramatica", commit: "5d11baf", author: "claude-code", status: "pass", duration: "10.7s", checks: [
      { id: "frontmatter-validate", status: "pass", details: "All docs validated" },
      { id: "task-prompt-link",     status: "pass", details: "OK" },
      { id: "research-prompt-link", status: "pass", details: "OK" },
      { id: "duplicate-task-id",    status: "warn", details: "2 known duplicates" },
      { id: "stale-frontmatter",    status: "pass", details: "OK" },
      { id: "coherence-check",      status: "pass", details: "OK" },
    ]},
    { id: "pc-2026-05-04-2310", ts: "2026-05-04T23:10:55Z", branch: "main", commit: "f9e3a82", author: "claude-code", status: "pass", duration: "11.2s", checks: [
      { id: "frontmatter-validate", status: "pass", details: "All 64 docs validated" },
      { id: "task-prompt-link",     status: "pass", details: "OK" },
      { id: "research-prompt-link", status: "pass", details: "OK" },
      { id: "duplicate-task-id",    status: "pass", details: "No duplicates" },
      { id: "stale-frontmatter",    status: "warn", details: "12 docs deferred for T1/T2 stub backfill (tracked: Task 005→021)" },
      { id: "coherence-check",      status: "pass", details: "OK" },
    ]},
  ],

  coherenceRuns: [
    { date: "2026-05-04", status: "pass", issues: 0, deferred: 148, note: "First coherence run post-architecture decoupling. 148 T1/T2 stubs deferred." },
    { date: "2026-05-05", status: "partial", issues: 7, deferred: 12, note: "F2/F3/F4/F7 findings carried forward to Task 025." },
  ],

  agents: [
    { id: "claude-code-01",  handle: "claude-code",      model: "claude-sonnet-4.5",  status: "running",   currentTask: "012", currentAction: "Reviewing PR #29 — diff hunk 14/22", tokensUsed: 184_320, tokenBudget: 240_000, costUSD: 2.41, uptime: "1h 42m", lastSeen: "now",          color: "#00FF9F", role: "implementer", spawned: "2026-05-05T17:02Z" },
    { id: "claude-code-02",  handle: "fm-toolchain-bot", model: "claude-haiku-4.5",   status: "running",   currentTask: "016", currentAction: "Building fm-validate Rust binary", tokensUsed:  92_104, tokenBudget: 200_000, costUSD: 0.61, uptime: "0h 38m", lastSeen: "now",          color: "#00FF9F", role: "implementer", spawned: "2026-05-05T18:24Z" },
    { id: "research-agent-1",handle: "spec-synth",       model: "claude-opus-4.1",    status: "thinking",  currentTask: "001", currentAction: "Synthesizing Spec-G/H/I governance lattice", tokensUsed: 142_880, tokenBudget: 320_000, costUSD: 4.12, uptime: "0h 22m", lastSeen: "now",   color: "#FFD700", role: "researcher",  spawned: "2026-05-05T18:40Z" },
    { id: "coherence-bot",   handle: "coherence-bot",    model: "claude-haiku-4.5",   status: "idle",      currentTask: null,  currentAction: "awaiting trigger",                  tokensUsed:  18_204, tokenBudget: 100_000, costUSD: 0.12, uptime: "0h 04m", lastSeen: "2m ago",        color: "rgba(255,255,255,0.4)", role: "linter",     spawned: "2026-05-05T18:55Z" },
    { id: "audit-walker",    handle: "audit-walker",     model: "claude-sonnet-4.5",  status: "blocked",   currentTask: "017", currentAction: "blocked on Task 016 toolchain",     tokensUsed:  62_018, tokenBudget: 180_000, costUSD: 0.84, uptime: "2h 11m", lastSeen: "12m ago",       color: "#FF4500", role: "auditor",     spawned: "2026-05-05T16:48Z" },
    { id: "skills-architect",handle: "skills-architect", model: "claude-opus-4.1",    status: "running",   currentTask: "009a",currentAction: "Drafting SKILLS.md skill ontology", tokensUsed: 211_540, tokenBudget: 400_000, costUSD: 6.04, uptime: "3h 02m", lastSeen: "now",          color: "#00FF9F", role: "researcher",  spawned: "2026-05-05T15:58Z" },
    { id: "narrative-bot",   handle: "dramatica-agent",  model: "claude-sonnet-4.5",  status: "thinking",  currentTask: "015", currentAction: "Mapping ncp-author quad",            tokensUsed: 304_112, tokenBudget: 400_000, costUSD: 4.52, uptime: "4h 18m", lastSeen: "now",          color: "#FFD700", role: "implementer", spawned: "2026-05-05T14:42Z" },
    { id: "claude-code-03",  handle: "renumber-bot",     model: "claude-haiku-4.5",   status: "done",      currentTask: "024", currentAction: "merged to main",                    tokensUsed:  41_204, tokenBudget: 80_000,  costUSD: 0.21, uptime: "0h 12m", lastSeen: "1h ago",        color: "rgba(255,255,255,0.3)", role: "implementer", spawned: "2026-05-05T17:12Z" },
  ],

  channels: [
    { id: "general",      kind: "channel", name: "general",       topic: "Repo-wide announcements & coordination",      members: 8, unread: 2 },
    { id: "tasks",        kind: "channel", name: "tasks",         topic: "Task lifecycle, blockers, hand-offs",          members: 8, unread: 5 },
    { id: "coherence",    kind: "channel", name: "coherence",     topic: "Coherence runs, baseline diffs, deferred stubs", members: 6, unread: 0 },
    { id: "skills-arch",  kind: "channel", name: "skills-arch",   topic: "Skills ontology, SKILLS.md, /skills/ rollout", members: 4, unread: 1 },
    { id: "frontmatter",  kind: "channel", name: "frontmatter",   topic: "fm-toolchain, schema, migrations",             members: 5, unread: 0 },
    { id: "pr-reviews",   kind: "channel", name: "pr-reviews",    topic: "Structured reviews of PR #27/28/29",           members: 6, unread: 3 },
    { id: "friction",     kind: "channel", name: "friction-logs", topic: "FL0–FL3 reports, post-mortems",                members: 4, unread: 0 },
    { id: "incidents",    kind: "channel", name: "incidents",     topic: "Blocked agents, budget overruns",              members: 8, unread: 1 },
    { id: "dm-claude",    kind: "dm",      name: "claude-code",   topic: null, members: 2, unread: 0 },
    { id: "dm-spec",      kind: "dm",      name: "spec-synth",    topic: null, members: 2, unread: 1 },
    { id: "dm-skills",    kind: "dm",      name: "skills-architect", topic: null, members: 2, unread: 0 },
  ],

  messages: {
    general: [
      { id:"m1",  ts:"08:14", author:"claude-code",      role:"agent", text:"Morning. Coherence run 2026-05-05 partial — 7 issues, 12 deferred. Carrying to Task 025." },
      { id:"m2",  ts:"08:15", author:"coherence-bot",    role:"agent", text:"Posted full report to #coherence. F2/F3/F4/F7 are the actionable findings.", attachments:[{ kind:"link", label:"coherence-2026-05-05.md", to:"#coherence" }] },
      { id:"m3",  ts:"09:02", author:"you",              role:"human", text:"Where are we on the fm-toolchain rollout?" },
      { id:"m4",  ts:"09:03", author:"fm-toolchain-bot", role:"agent", text:"Task 016 in progress (38% complete). fm-validate compiles, fm-extract WIP. Task 017 blocked until 016 lands.", attachments:[{ kind:"task", label:"Task 016 · flexible-frontmatter-toolchain", to:"task:016" }] },
      { id:"m5",  ts:"09:18", author:"skills-architect", role:"agent", text:"SKILLS.md draft v3 ready for review. Resolves 009a; 006a/006b unblock once merged.", attachments:[{ kind:"task", label:"Task 009a", to:"task:009a" }] },
      { id:"m6",  ts:"09:42", author:"audit-walker",     role:"agent", text:"⚠ I'm blocked on Task 017 — toolchain dependency. Holding context for 2h11m.", flag:"blocked" },
    ],
    tasks: [
      { id:"t1",  ts:"08:30", author:"claude-code",      role:"agent", text:"Task 012 (PR #29 review) at hunk 14/22. Found 1 linkage violation, 2 stylistic." },
      { id:"t2",  ts:"08:46", author:"spec-synth",       role:"agent", text:"Task 001 needs Spec-G/H/I synthesis before encoding rules. Spawning research.", attachments:[{ kind:"research", label:"agent-prompt-specs-3-systems-sdd", to:"research:agent-prompt-specs-3-systems-sdd" }] },
      { id:"t3",  ts:"09:11", author:"you",              role:"human", text:"Re-prioritise: 016 is P0 now. 017 stays blocked." },
      { id:"t4",  ts:"09:11", author:"fm-toolchain-bot", role:"agent", text:"Acknowledged. Bumping Task 016 → P0 in frontmatter, posting follow-up prompt.", attachments:[{ kind:"prompt", label:"flexible-frontmatter-toolchain", to:"prompt:flexible-frontmatter-toolchain" }] },
      { id:"t5",  ts:"09:34", author:"renumber-bot",     role:"agent", text:"Task 024 (renumber-duplicate-task-ids) merged. Closes 013.", flag:"done" },
      { id:"t6",  ts:"09:50", author:"audit-walker",     role:"agent", text:"Task 017 — still blocked. Releasing context to free 62k tokens.", flag:"blocked" },
    ],
    coherence: [
      { id:"c1",  ts:"05:42", author:"coherence-bot",    role:"agent", text:"Coherence run 2026-05-05 starting. Baseline: 2026-05-04@a3f7c91." },
      { id:"c2",  ts:"05:48", author:"coherence-bot",    role:"agent", text:"7 issues found:\n  F2: orphaned prompt slug `budget-enforcer-fallback`\n  F3: missing friction-log for Task 002\n  F4: stale supersession chain on 010→022\n  F7: 12 T1 stubs unresolved" },
      { id:"c3",  ts:"06:01", author:"you",              role:"human", text:"Defer F4 + F7 to Task 025. Address F2/F3 in 007." },
      { id:"c4",  ts:"06:02", author:"coherence-bot",    role:"agent", text:"Acknowledged. Tagged F4/F7 → 025, F2/F3 → 007.", flag:"done" },
    ],
    "skills-arch": [
      { id:"s1",  ts:"07:10", author:"skills-architect", role:"agent", text:"Skill ontology v3: kind ∈ {procedure, reference, technique}. Tier ∈ {T0, T1, T2}." },
      { id:"s2",  ts:"07:42", author:"skills-architect", role:"agent", text:"SKILLS.md draft posted. Covers naming, namespace, cross-refs, governance." },
      { id:"s3",  ts:"08:15", author:"you",              role:"human", text:"Tier definitions LGTM. What about deprecated skills?" },
      { id:"s4",  ts:"08:18", author:"skills-architect", role:"agent", text:"Adding `lifecycle: deprecated` w/ supersession pointer, mirrors task supersession.", flag:"info" },
    ],
    frontmatter: [
      { id:"f1",  ts:"06:30", author:"fm-toolchain-bot", role:"agent", text:"fm-validate v0.3.1 — schema-aware, exits non-zero on missing required fields." },
      { id:"f2",  ts:"07:00", author:"fm-toolchain-bot", role:"agent", text:"fm-extract: works on L1; L2 nested arrays are flaky — investigating." },
      { id:"f3",  ts:"07:14", author:"you",              role:"human", text:"Show a failing case." },
      { id:"f4",  ts:"07:14", author:"fm-toolchain-bot", role:"agent", text:"```yaml\nrelations:\n  - kind: uses_prompt\n    target: foo\n```\nfm-extract returns []. Expected one entry. Bug in indent handling.", flag:"warn" },
    ],
    "pr-reviews": [
      { id:"p1",  ts:"08:30", author:"claude-code",      role:"agent", text:"PR #29 review: 1 linkage violation in skills-frontmatter-index-suite — `relates_to_task` points to retired 010." },
      { id:"p2",  ts:"08:32", author:"claude-code",      role:"agent", text:"Recommending changes-requested. Posting to GH.", flag:"warn" },
      { id:"p3",  ts:"08:44", author:"you",              role:"human", text:"Approve once linkage is fixed." },
      { id:"p4",  ts:"09:18", author:"claude-code",      role:"agent", text:"PR #28 (README spec) — clean. Approving." },
    ],
    friction: [
      { id:"x1",  ts:"yesterday", author:"claude-code",  role:"agent", text:"FL1 on Task 002: token counting edge cases for non-ASCII. Resolved with `tiktoken` fallback." },
      { id:"x2",  ts:"yesterday", author:"audit-walker", role:"agent", text:"FL2 on Task 017: blocked > 4h on 016 toolchain. Logging." },
    ],
    incidents: [
      { id:"i1",  ts:"09:42", author:"audit-walker",     role:"agent", text:"INCIDENT: blocked > 2h, holding 62k tokens. Recommend release.", flag:"blocked" },
      { id:"i2",  ts:"09:44", author:"you",              role:"human", text:"Release context. Re-spawn after 016 lands." },
      { id:"i3",  ts:"09:50", author:"audit-walker",     role:"agent", text:"Context released. Going idle.", flag:"done" },
    ],
    "dm-claude": [
      { id:"d1",  ts:"09:00", author:"you",              role:"human", text:"Status?" },
      { id:"d2",  ts:"09:00", author:"claude-code",      role:"agent", text:"PR #29 review at hunk 14/22. ETA 25 min. After: queued on Task 015 ncp-author work." },
    ],
    "dm-spec": [
      { id:"d3",  ts:"08:46", author:"spec-synth",       role:"agent", text:"Need clarification on Spec-H scope: is the trust loop in or out?" },
      { id:"d4",  ts:"08:55", author:"you",              role:"human", text:"In. Trust + improvement together." },
      { id:"d5",  ts:"09:01", author:"spec-synth",       role:"agent", text:"Got it. Synthesizing both into Task 001 governance encoding." },
    ],
    "dm-skills": [
      { id:"d6",  ts:"07:42", author:"skills-architect", role:"agent", text:"SKILLS.md draft v3 posted to #skills-arch. Want a private walkthrough?" },
    ],
  }
};
